- name: Set DA Account
  ansible.windows.win_user:
    fullname: Domain Administrator
    name: "{{ da_user }}"
    password: "{{ da_password }}"
- name: Set upstream DNS server 
  ansible.windows.win_dns_client:
    adapter_names: Ethernet
    ipv4_addresses:
      - "{{ upstream_dns }}"
- name: Disable Firewall
  win_firewall:
    state: disabled
    profiles:
      - Domain
      - Private
      - Public
- name: Change the hostname
  ansible.windows.win_hostname:
    name: "{{ dc_hostname }}"
  register: res
- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required
- name: Install Active Directory
  ansible.windows.win_feature: >
    name=AD-Domain-Services
    include_management_tools=yes
    include_sub_features=yes
    state=present
  register: result
- name: Create Domain
  microsoft.ad.domain:
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ recovery_password }}"
    reboot: true
- name: Set internal DNS server
  ansible.windows.win_dns_client:
    adapter_names: Ethernet
    ipv4_addresses:
    - '127.0.0.1'
- name: Create reverse DNS zone
  ansible.windows.win_powershell: 
    script: |
      Add-DnsServerPrimaryZone -NetworkID "{{ reverse_dns_zone }}" -ReplicationScope Forest
  retries: 30
  delay: 60
  register: result
  until: result is succeeded

