  keepass_dbx: "~/seclab/seclab.kdbx"
  ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  ansible_user: "{{ lookup('viczem.keepass.keepass', 'Seclab/seclab_user', 'username') }}"
  ansible_password: "{{ lookup('viczem.keepass.keepass', 'Seclab/seclab_user', 'password') }}"
  ansible_connection: ssh
