---
- name: Create ASREP-Roastable User
  vars:
    user: "{{ users['asreproast'] }}"
    spn_server: "{{ servers | random }}"
    spn_service: "{{ services | random  }} "
  microsoft.ad.user:
    domain_server: "{{ domain }}"
    domain_username: "{{ da_user }}"
    domain_password: "{{ da_password }}"
    name: "{{ user['username'] }}"
    display_name: "{{ user['display_name'] }}"
    firstname: "{{ user['first_name'] }}"
    surname: "{{ user['last_name'] }}"
    password_never_expires: true
    password: "{{ user['password'] }}"
  register: asrep_user
- name: Display ASREP-Roast User
  ansible.builtin.debug:
    msg: "{{ asrep_user }}"
- name: Make User ASREP-Roastable
  ansible.windows.win_powershell:
    script: | 
      Set-ADAccountPassword -Identity {{ asrep_user['distinguished_name']}} -NewPassword (ConvertTo-SecureString -AsPlainText {{ bad_passwords | random }} -Force)
      Set-ADAccountControl -Identity {{ user['username'] }} -DoesNotRequirePreAuth $true
      
  

