---
- name: Create ASREP-Roastable User
  vars:
    asrep_user: "{{ users['asreproast'] }}"
  microsoft.ad.user:
    domain_server: "{{ domain }}"
    domain_username: "{{ da_user }}"
    domain_password: "{{ da_password }}"
    name: "{{ asrep_user['username'] }}"
    display_name: "{{ asrep_user['display_name'] }}"
    firstname: "{{ asrep_user['first_name'] }}"
    surname: "{{ asrep_user['last_name'] }}"
    password_never_expires: true
    password: "{{ asrep_user['password'] }}"
  register: asrep_user_created
- name: Display ASREP-Roast User
  ansible.builtin.debug:
    msg: "{{ asrep_user_created }}"
- name: Make User ASREP-Roastable
  vars:
    asrep_user: "{{ users['asreproast'] }}"
  ansible.windows.win_powershell:
    script: | 
      Set-ADAccountPassword -Identity "{{ asrep_user_created['distinguished_name']}}" -NewPassword (ConvertTo-SecureString -AsPlainText "{{ bad_passwords | random }}" -Force)
      Set-ADAccountControl -Identity "{{ asrep_user['username'] }}" -DoesNotRequirePreAuth $true
      
  

