---
- name: Install Wireguard
  ansible.builtin.apt:
    update_cache: true
    name:
      - wireguard
- name: Generate Wireguard Private key
  ansible.builtin.shell:
    cmd: "wg genkey"
  register: privkey
- name: Generate Wireguard Public key
  ansible.builtin.shell:
    cmd: "echo {{ privkey['stdout'] }} | wg pubkey"
  register: pubkey
- name: Print keys
  ansible.builtin.debug:
    msg: "{{ {
              'private_key': privkey['stdout'], 
              'public_key': pubkey['stdout']
              }
            }}"
- name: Install WG Config
  ansible.builtin.template:
    src: wg.conf.j2
    dest: /etc/wireguard/{{ wg_network_name }}.conf
    owner: root
    group: root
    mode: 0600
- name: Enable/Start WG service
  ansible.builtin.systemd_service:
    name: "wg-quick@{{ wg_network_name }}"
    enabled: true
    state: started
