---
- name: Install Nginx
  ansible.builtin.apt:
    pkg:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: latest
    update_cache: true
  tags: [always]
- name: Stop Nginx
  ansible.builtin.systemd:
    name: nginx
    state: stopped
  tags: [always]
- name: Retrieve Cert
  ansible.builtin.shell: 
    cmd: "certbot certonly --standalone -d {{ nginx_hostname }}.{{ domain }} --server https://{{ ca_host }}/acme/seclab/directory -n -m root@{{ ca_host }}"
    creates: /etc/letsencrypt/live
  tags: [always]
- name: Add Nginx Template
  ansible.builtin.template:
    src: site-config.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
  tags: [always]
- name: Add Index Template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
  tags: [always]
- name: Fix webroot permissions
  ansible.builtin.file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: true
  tags: [always]
- name: Start/Enable Nginx
  ansible.builtin.systemd:
    daemon-reload: true
    name: nginx
    state: started
    enabled: true
  tags: [always]
- name: Install Cronjob for Renewal
  ansible.builtin.template:
    src: certbot-cron
    dest: /etc/cron.d/certbot
    owner: root
    group: root  
  tags: [always]
- name: Enable PHP
  import_tasks: php.yml
  tags: [php]

  
