---
- name: Generate users
  hosts: localhost
  connection: local
  vars:
    num_users: 10
  tasks:
    - name: Run script
      ansible.builtin.command:
        cmd: ad-lab/generate_users.py
      register: g_u
    - name: Print FirstName
      ansible.builtin.debug:
        msg: "{{ g_u.stdout }}"
    # - name: Print FirstName
    #   ansible.builtin.debug:
    #     msg: "{{ first_names | random }}"
    #   with_sequence: "start=0 end={{ num_users }}"
    # - name: Print FirstNames
    #   ansible.builtin.debug:
    #     msg: "{{ lookup('ansible.builtin.random_choice', first_names) }}"
    #   with_sequence: "start=0 end={{ num_users }}"
    
- name: Create Domain Users
  vars_files:
    - ad-lab/vars.yml
  hosts: "{{ dc_hostname }}"
  tasks:
    - name: Create users
      microsoft.ad.user:
        domain_server: "{{ domain }}"
        domain_username: "{{ da_user }}"
        domain_password: "{{ da_password }}"
        name: "{{ item['username'] }}"
        display_name: "{{ item['display_name'] }}"
        firstname: "{{ item['first_name'] }}"
        surname: "{{ item['last_name'] }}"
        password: "{{ item['password'] }}"
        state: present
      with_items: "{{ users }}"

- name: Enable vulnerabilities
  vars_files:
    - ad-lab/vars.yml
  hosts: "{{ dc_hostname }}"
  tasks:
    - name: Enable DCSync Vulnerability
      ansible.builtin.import_tasks:
        file: ad-lab/dcsync.yml
      tags: [dcsync]
    - name: Debug Task
      ansible.builtin.debug:
        msg: "{{ servers }}"
