- name: Join Machine to a Domain
  hosts: windows-hosts
  gather_facts: true
  vars:
    domain: zeroday.local
    dns_server: 10.1.99.4
  tasks:
  - name: Pause Windows updates
    ansible.windows.win_updates:
      reject_list:
        - ".*"
  - name: Set DNS server to DC
    win_dns_client:
      adapter_names: 'Ethernet'
      ipv4_addresses:
       - '{{ dns_server }}'
  - name: Reboot Machine for Rename
    ansible.windows.win_reboot:
      msg: "Rebooting for Provisioning Name Change"
      pre_reboot_delay: 15
  - name: Join to Domain
    ansible.windows.win_domain_membership:
      dns_domain_name: zeroday.local
      hostname: "{{ ansible_facts['hostname'] }}"
      domain_admin_user: "{{ lookup('viczem.keepass.keepass', 'Seclab/seclab_windows', 'username') }}@{{ domain }}"
      domain_admin_password: "{{ lookup('viczem.keepass.keepass', 'Seclab/seclab_windows', 'password') }}"
      state: domain
    register: domain_state
  - name: Reboot Machine
    ansible.windows.win_reboot:
      msg: "Domain joined. Rebooting"
      pre_reboot_delay: 15
    when: domain_state.changed
  roles:
    - rdp
    - sysmon
