---
- name: Install ELK Stack
  hosts: siem.sec.lab
  vars:
    caddy_hostname: siem
  roles:
    - role: elk-stack
      become: true
      become_user: root
      tags: [install]
    - role: caddy
      become: true
      become_user: root
      vars:
        mode: reverse_proxy
        proxy_port: 5601
