---
- name: Install ELK Stack
  hosts: siem.sec.lab
  vars:
    caddy_hostname: siem
  roles:
    - role: elk-stack
      become: true
      become_user: root
      tags: [install]
    - role: caddy-reverse-proxy
      become: true
      become_user: root
      vars:
        proxy_port: 5601
      tags: [reverse-proxy]
