---
- name: Configure Malware Analysis SIEM
  hosts: mwl-siem.iso.sec.lab
  vars_prompt:
    - name: siem_password
      prompt: Splunk password (blank if Elastic)
      private: false
  vars:
    domain: iso.sec.lab
  roles:
    - role: elk-stack
      become: true
      become_user: root
      tags: ["elastic"]
    - role: splunk-server
      become: true
      become_user: root
      tags: ["splunk"]
    - role: caddy
      become: true
      become_user: root
      vars:
        mode: reverse_proxy
        proxy_port: 8000
      tags: ["splunk"]
    - role: caddy
      become: true
      become_user: root
      vars:
        mode: reverse_proxy
        proxy_port: 5601
      tags: ["elastic"]
