---
- name: Install Splunk Enterprise Server
  hosts: siem.sec.lab
  vars_prompt:
    - name: siem_password
      prompt: "Enter Splunk Admin Password"
      private: false
  become: true
  become_user: root
  roles:
    - role: splunk-server
      become: true
      become_user: root
      tags: [install]
    - role: caddy-reverse-proxy
      become: true
      become_user: root
      vars:
        proxy_port: 8000
      tags: [reverse-proxy]
    
