---
- name: Deploy Velociraptor Server
  hosts: all
  vars:
    proxy_port: 8889
    domain: iso.sec.lab
    webroot: /var/www/html
    fileserver_port: 8000
  roles:
    - role: caddy
      become: true
      become_user: root
      vars:
        mode: reverse_proxy
    - role: velociraptor-server
      become: true
      become_user: root
      vars:
        velociraptor_version: "0.74"
        velociraptor_version_long: "0.74.1"
