network:
  ethernets:
    ens18:
      dhcp4: false
      addresses:
        - 192.168.99.2/24
      nameservers:
          addresses:
            - 192.168.99.1
      routes:
        - to: 0.0.0.0/0
          via: 192.168.99.1
          metric: 99
    ens19:
      dhcp4: true
      routes:
        - to: 10.1.99.0/24
          via: 10.1.99.1
          metric: 100
  version: 2
