network:
  ethernets:
    enp6s18:
      dhcp4: false
      addresses:
        - 192.168.99.5/24
      nameservers:
          addresses:
            - 192.168.99.1
          search:
            - sec.lab
      routes:
      - to: 0.0.0.0/0
        via: 192.168.99.1
        metric: 99
  version: 2
